version: '3'
services:
  miner:
    tty: true
    stdin_open: true
    build: .
    ports:
      - '18400:18443'
      - '18500:18444'
    expose:
      - '18444'
    command:
      ['bitcoind', '-regtest', '-printtoconsole', '-addnode=node1:18444', '-addnode=node2:18444']
  node1:
    tty: true
    build: .
    ports:
      - '18401:18443'
      - '18501:18444'
    expose:
      - '18444'
    command:
      ['bitcoind', '-regtest', '-printtoconsole', '-addnode=miner:18444', '-addnode=node2:18444']
  node2:
    tty: true
    build: .
    ports:
      - '18402:18443'
      - '18502:18444'
    expose:
      - '18444'
    command:
      ['bitcoind', '-regtest', '-printtoconsole', '-addnode=node1:18444', '-addnode=miner:18444']
